### ISSUE TITLE
sidebar is disappearing after reload

### ISSUE THREAD

**Issue by akoskm** [HYP3R00T/CelestialDocs#3] opened 2024-10-10 05:49 UTC
**Describe the bug**
Left sidebar disappears after refreshing the page.

**To Reproduce**
1. Go to localhost:4321
2. Refresh the page
3. Left sidebar isn't visible anymore

**Expected behavior**
The sidebar should be visible

**Screenshots**

https://github.com/user-attachments/assets/3c9bde33-7ce8-468e-a629-c65c1d31df42

Can be reproduced in https://github.com/akoskm/react-crash-course-web or on https://reactcc.netlify.app.

The console also contains a lot of errors: 
![image](https://github.com/user-attachments/assets/d317b573-275e-4f05-8d47-06c1916a7203)

`npm run build` passes without any, but the bug is also present with `npm run preview`

**Comment by HYP3R00T** [comment] 2024-10-10 05:53
Thanks @akoskm for reporting the bug. I am looking into it.

**Comment by akoskm** [comment] 2024-10-10 05:53
thanks @HYP3R00T 🙌

Also, if you go back to / and start the course again, the sidebar reappears.

https://github.com/user-attachments/assets/3fd84917-f5b1-4acf-9f7b-8636f80fbe66

**Comment by HYP3R00T** [comment] 2024-10-10 06:18
@akoskm I am sorry but I am unable to recreate the bug you reported.

### What I have tried so far?

- I have cloned your repo and started the server locally. The side nav is working as expected. I even checked the console, and there was no error as you showed in the snapshot. 
- I switched browsers to Brave, Google and Edge and still can't reproduce the error. 
- I checked your hosted instance and it's working fine even there. 
- I tried in incognito mode as well.

Given that I am unable to recreate the bug, perhaps I can suggest that you try again after clearing the cache and cookies. Or try a different browser.

**Comment by akoskm** [comment] 2024-10-10 07:34
@HYP3R00T indeed. I just tried it in Brave and it seems to work, but:
 - on the left, when I'm on a page, for example Composition, the underline is missing
 - there are still bunch of errors in Brave, which I suspec is breaking the site

![image](https://github.com/user-attachments/assets/e850af56-cf52-4236-8867-990bb5829f5c)

Do you see these errors in Brave as well?

**Comment by HYP3R00T** [comment] 2024-10-10 07:42
@akoskm Yes. I saw these errors. I believe these are because of the sandbox. Not sure if I can do anything to it as it's not there in my original repo. Let me know if there need to be some modification needed in my repo to help you fix it. 

Regarding the underline, I never created that. There has never been an underline. I will add that feature in the next release. I am planning to completely get rid of React and use pure Astro components. I am working on a component and UI library purely based on Astro. So, this feature will take some time. But if you need it, you can modify the code if you are a bit familiar with astro and tailwind CSS.
```
src/components/docs/SideNavMenu.astro
```

**Comment by akoskm** [comment] 2024-10-10 08:01
@HYP3R00T I'm totally confused 😃 on my end the underline is there because text-primary gets applied to the menu that matches the current url, while other menu items get the no-underline, which makes them not underlined.

https://github.com/HYP3R00T/CelestialDocs/blob/822bc1ba0f522ab0f76080d6c7313daf32d57e29/src/components/docs/SideNavMenu.astro#L22

This should also mark the active menu item text-primary, which isn't happening in your demo either. 

**EDIT** yes, thanks for pointing out. the other errors are coming from codesandbox

**Comment by HYP3R00T** [comment] 2024-10-10 08:18
Apologies for all the confusion. To be honest, I forgot the code and how I did what I did. I have been focusing on another project. If the underline exists then it should show up as it's nothing more than a simple css. Allow me to take a look at it.

**Comment by akoskm** [comment] 2024-10-10 08:40
No worries @HYP3R00T! At least we figured out this part 😃 FYI I'm also going with Astro's Document template for my project so I probably can't test if you make any fixes to this project. Thanks for your work 🙌

**Comment by HYP3R00T** [comment] 2024-10-10 08:42
@akoskm Thanks for checking out my project. With this, I am closing this issue.

**Closed as completed by HYP3R00T** 2024-10-10 08:42 UTC
